# Generated by Django 3.1.2 on 2020-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headLine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_summary',
            field=models.TextField(default='TEST SUMMARY'),
            preserve_default=False,
        ),
    ]
